### ISSUE TITLE
Create me

### ISSUE THREAD

**Issue by clue** [clue/reactphp-csv#1]

**Comment by Rakdar** [comment]
Hey,
i just went to your profile and by coincidence i saw you created this repository. As i already did something similar i thought i should give you a heads-up: [https://github.com/Rakdar/reactphp-csv](https://github.com/Rakdar/reactphp-csv)

**Comment by clue** [comment]
@Rakdar Thank you very much for pointing me to your repository, much appreciated! :+1: 

I've started working on this project a while back and this is pretty much only lacking some more documentation. After taking a look at your repository, I currently have no plans to continue working on this. Your project implements all the features that were required for my use case at the moment! :tada: 

Maybe add your project to https://github.com/reactphp/react/wiki/Users to spread the word? :shipit:

**Comment by Rakdar** [comment]
That is great to hear!

I also just added my library to the ReactPHP wiki page. :blush:

**Comment by clue** [comment]
@Rakdar Thanks for your project, after toying around with it for a while and stumbling over https://github.com/Rakdar/reactphp-csv/issues/2 I've decided to just push my initial version that has been ready for a few months already.

I've just pushed the initial commit via 7f45bc22b83c1d7aff03b9bd415580ac57820c3f :shipit:
